#!/usr/bin/env python3
"""Render guarded apply or rollback SQL from an account organization plan."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any


IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def quote_identifier(value: str) -> str:
    if not IDENTIFIER_RE.fullmatch(value):
        raise ValueError(f"unsafe SQL identifier: {value!r}")
    return '"' + value.replace('"', '""') + '"'


def write_text_0600(path: str, text: str) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
    finally:
        try:
            os.chmod(target, 0o600)
        except FileNotFoundError:
            pass


def load_plan(path: str) -> tuple[dict[str, Any], str]:
    raw = Path(path).read_bytes()
    payload = json.loads(raw)
    if (
        not isinstance(payload, dict)
        or payload.get("schema_version") != 6
        or payload.get("operation") != "sub2api-account-name-organize"
    ):
        raise ValueError("unsupported or malformed plan")
    changes = payload.get("changes")
    if not isinstance(changes, list) or not changes:
        raise ValueError("plan has no name changes")
    return payload, hashlib.sha256(raw).hexdigest()


def render_sql(plan: dict[str, Any], plan_sha256: str, direction: str, schema: str) -> str:
    if direction not in {"apply", "rollback"}:
        raise ValueError(f"unsupported direction: {direction!r}")
    rows: list[dict[str, Any]] = []
    seen: set[int] = set()
    for change in plan["changes"]:
        if not isinstance(change, dict):
            raise ValueError("plan change is not an object")
        aid = int(change["id"])
        if aid <= 0 or aid in seen:
            raise ValueError(f"invalid or duplicate account id: {aid}")
        seen.add(aid)
        old_name = change.get("old_name")
        new_name = change.get("new_name")
        if not isinstance(old_name, str) or not isinstance(new_name, str):
            raise ValueError(f"invalid names for account {aid}")
        expected, replacement = (old_name, new_name) if direction == "apply" else (new_name, old_name)
        if not expected or not replacement or len(replacement) > 100 or "\x00" in replacement:
            raise ValueError(f"unsafe replacement name for account {aid}")
        rows.append({"id": aid, "expected_name": expected, "replacement_name": replacement})

    encoded = base64.b64encode(
        json.dumps(rows, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    ).decode("ascii")
    qschema = quote_identifier(schema)
    accounts = f"{qschema}.\"accounts\""
    outbox = f"{qschema}.\"scheduler_outbox\""
    return f"""\\set ON_ERROR_STOP on
-- Generated by sub2api-account-organizer.
-- Direction: {direction}
-- Plan SHA256: {plan_sha256}
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '2min';
SELECT pg_advisory_xact_lock(hashtextextended('sub2api.accounts.display_organizer', 0));

CREATE TEMP TABLE account_name_organizer_plan (
    id BIGINT PRIMARY KEY,
    expected_name TEXT NOT NULL,
    replacement_name TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO account_name_organizer_plan (id, expected_name, replacement_name)
SELECT id, expected_name, replacement_name
FROM jsonb_to_recordset(
    convert_from(decode('{encoded}', 'base64'), 'UTF8')::jsonb
) AS item(id BIGINT, expected_name TEXT, replacement_name TEXT);

DO $account_name_organizer$
DECLARE
    expected_count BIGINT;
    matched_count BIGINT;
    updated_count BIGINT;
BEGIN
    SELECT COUNT(*) INTO expected_count FROM account_name_organizer_plan;
    IF expected_count = 0 THEN
        RAISE EXCEPTION 'account organizer plan is empty';
    END IF;
    IF EXISTS (
        SELECT 1 FROM account_name_organizer_plan
        WHERE replacement_name = '' OR char_length(replacement_name) > 100
    ) THEN
        RAISE EXCEPTION 'account organizer plan contains an invalid replacement name';
    END IF;

    SELECT COUNT(*) INTO matched_count
    FROM {accounts} AS account
    JOIN account_name_organizer_plan AS plan ON plan.id = account.id
    WHERE account.deleted_at IS NULL
      AND account.name = plan.expected_name;
    IF matched_count <> expected_count THEN
        RAISE EXCEPTION 'account organizer precondition failed: matched %, expected %', matched_count, expected_count;
    END IF;

    UPDATE {accounts} AS account
    SET name = plan.replacement_name,
        updated_at = NOW()
    FROM account_name_organizer_plan AS plan
    WHERE account.id = plan.id
      AND account.deleted_at IS NULL
      AND account.name = plan.expected_name;
    GET DIAGNOSTICS updated_count = ROW_COUNT;
    IF updated_count <> expected_count THEN
        RAISE EXCEPTION 'account organizer update count mismatch: updated %, expected %', updated_count, expected_count;
    END IF;

    INSERT INTO {outbox} (event_type, account_id, payload)
    SELECT 'account_changed', id, '{{"reason":"account_name_organized"}}'::jsonb
    FROM account_name_organizer_plan;
END
$account_name_organizer$;

SELECT COUNT(*) AS verified_rows
FROM {accounts} AS account
JOIN account_name_organizer_plan AS plan ON plan.id = account.id
WHERE account.name = plan.replacement_name
  AND account.deleted_at IS NULL;
COMMIT;
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", required=True)
    parser.add_argument("--direction", choices=("apply", "rollback"), required=True)
    parser.add_argument("--schema", default="public")
    parser.add_argument("--output", required=True, help="SQL output path (mode 0600)")
    args = parser.parse_args()
    try:
        plan, digest = load_plan(args.plan)
        sql = render_sql(plan, digest, args.direction, args.schema)
        write_text_0600(args.output, sql)
        print(json.dumps({"direction": args.direction, "plan_sha256": digest, "output": str(Path(args.output).resolve())}, sort_keys=True))
        return 0
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
